name: Lightspeed

on: [push, pull_request]
jobs:
  lightspeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install lightspeed-photon
        run:
          pip install git+https://github.com/goneri/lightspeed-photon

      - name: Run lightspeed-photon
        run: lightspeed-photon tests/photon/ --debug
        env:
          LIGHTSPEED_TOKEN: ${{ secrets.SECRET_TOKEN }}
